apiVersion: v1
kind: PersistentVolume
metadata:
  name: moodledata-pv
#[autopilot-persistent-volume-limitation]":["Persistent Volume sources can only be of types [csi nfs gcePersistentDisk] within Autopilot.
  labels:
    type: nfs
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs: 
      path: /tmp/moodledata
      server: 10.67.112.178:/moodledata

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: moodledata-claim
  labels:
    app: moodle
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi