apiVersion: apps/v1
kind: Deployment
metadata:
  name: moodle
  labels:
    app: moodle
    
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: moodle
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: moodle
        tier: frontend
    spec:
      containers:
      - image: bitnami/moodle:latest
        name: moodle
        env:
          - name: ALLOW_EMPTY_PASSWORD
            value: 'no'
          - name: MOODLE_DATABASE_USER
            value: moodle
          - name: MOODLE_DATABASE_PASSWORD
            value: moodle
          - name: MOODLE_DATABASE_NAME
            value: moodle
          - name: MOODLE_DATABASE_TYPE
            value: pgsql
          - name: MOODLE_DATABASE_HOST
            value: $REPLACE_WITH_POSTGRES_HOST
          - name: MOODLE_DATABASE_PORT_NUMBER
            value: '5432'
        volumeMounts:
        - name: moodledata
          mountPath: /moodle/data
      volumes:
      - name: moodledata
        persistentVolumeClaim:
          claimName: moodledata-claim

