apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-postgresql-pv
  labels:
    type: nfs
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  nfs: 
      path: /tmp/pgdata
      server: $REPLACE_WITH_NFS_MOUNT
