#bind the role on the account to apply the permissions and rules on the latter
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: traefik-role-binding

# roleRef is the Kubernetes reference to the role created in 00-role.yml.
roleRef: 
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole 
  name: traefik-role
  
#subjects is the list of accounts reference.
#In this guide, it only contains the account created in 00-account.yml
subjects:
  - kind: ServiceAccount
    name: traefik-account
    namespace: default # Using "default" because we did not specify a namespace when creating the ClusterAccount.